{% set name = "genespeak" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genespeak-{{ version }}.tar.gz
  sha256: 349bf672831c431c9201911c16fe80a820375fc8c1b7669f746ecc8905b1ca6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - genespeak
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sugatoray/genespeak/
  summary: A library to encode text as DNA and decode DNA to text.
  license: MIT
  license_file: LICENSE
  description: |    
    <a href="https://github.com/sugatoray/genespeak/">
      <img src="https://raw.githubusercontent.com/sugatoray/genespeak/master/docs/assets/images/genespeak_banner_01.png" alt="genespeak-banner" />
    </a>
    
    GeneSpeak allows you to encode regular text as DNA using 
    base-pairs (`A`, `C`, `G`, `T`) and convert back to the 
    original text. Text encoding is done for both `ascii` and 
    `utf-8` characters based on the `strategy` keyword argument.

    PyPI: [https://pypi.org/project/genespeak/](https://pypi.org/project/genespeak/)

  doc_url: https://sugatoray.github.io/genespeak/
  dev_url: https://github.com/sugatoray/genespeak/

extra:
  recipe-maintainers:
    - sugatoray
